services:
  - type: web
    name: api-dsm-4-frontend
    runtime: node
    plan: free
    rootDir: app
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3010
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: API_SERVER_URL
        sync: false
      - key: NEXT_PUBLIC_PARAMETERS_API_URL
        sync: false
      - key: NEXT_PUBLIC_STATIONS_API_URL
        sync: false
